// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: tiktok/im/v1/im.proto

package tiktokpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EmptyMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmptyMessage) Reset() {
	*x = EmptyMessage{}
	mi := &file_tiktok_im_v1_im_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmptyMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmptyMessage) ProtoMessage() {}

func (x *EmptyMessage) ProtoReflect() protoreflect.Message {
	mi := &file_tiktok_im_v1_im_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmptyMessage.ProtoReflect.Descriptor instead.
func (*EmptyMessage) Descriptor() ([]byte, []int) {
	return file_tiktok_im_v1_im_proto_rawDescGZIP(), []int{0}
}

type MetadataKV struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           *string                `protobuf:"bytes,1,opt,name=key" json:"key,omitempty"`
	Value         *string                `protobuf:"bytes,2,opt,name=value" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetadataKV) Reset() {
	*x = MetadataKV{}
	mi := &file_tiktok_im_v1_im_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetadataKV) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetadataKV) ProtoMessage() {}

func (x *MetadataKV) ProtoReflect() protoreflect.Message {
	mi := &file_tiktok_im_v1_im_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetadataKV.ProtoReflect.Descriptor instead.
func (*MetadataKV) Descriptor() ([]byte, []int) {
	return file_tiktok_im_v1_im_proto_rawDescGZIP(), []int{1}
}

func (x *MetadataKV) GetKey() string {
	if x != nil && x.Key != nil {
		return *x.Key
	}
	return ""
}

func (x *MetadataKV) GetValue() string {
	if x != nil && x.Value != nil {
		return *x.Value
	}
	return ""
}

type MetadataTag struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           *string                `protobuf:"bytes,1,opt,name=key" json:"key,omitempty"`
	Value         []byte                 `protobuf:"bytes,2,opt,name=value" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetadataTag) Reset() {
	*x = MetadataTag{}
	mi := &file_tiktok_im_v1_im_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetadataTag) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetadataTag) ProtoMessage() {}

func (x *MetadataTag) ProtoReflect() protoreflect.Message {
	mi := &file_tiktok_im_v1_im_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetadataTag.ProtoReflect.Descriptor instead.
func (*MetadataTag) Descriptor() ([]byte, []int) {
	return file_tiktok_im_v1_im_proto_rawDescGZIP(), []int{2}
}

func (x *MetadataTag) GetKey() string {
	if x != nil && x.Key != nil {
		return *x.Key
	}
	return ""
}

func (x *MetadataTag) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

type InboxRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	MessageType    *uint64                `protobuf:"varint,1,opt,name=message_type,json=messageType" json:"message_type,omitempty"`
	SubCommand     *uint64                `protobuf:"varint,2,opt,name=sub_command,json=subCommand" json:"sub_command,omitempty"`
	ClientVersion  *string                `protobuf:"bytes,3,opt,name=client_version,json=clientVersion" json:"client_version,omitempty"`
	Options        *EmptyMessage          `protobuf:"bytes,4,opt,name=options" json:"options,omitempty"`
	PlatformFlag   *uint64                `protobuf:"varint,5,opt,name=platform_flag,json=platformFlag" json:"platform_flag,omitempty"`
	Reserved_6     *uint64                `protobuf:"varint,6,opt,name=reserved_6,json=reserved6" json:"reserved_6,omitempty"`
	GitHash        *string                `protobuf:"bytes,7,opt,name=git_hash,json=gitHash" json:"git_hash,omitempty"`
	Payload        *InboxRequestPayload   `protobuf:"bytes,8,opt,name=payload" json:"payload,omitempty"`
	DeviceId       *string                `protobuf:"bytes,9,opt,name=device_id,json=deviceId" json:"device_id,omitempty"`
	ClientPlatform *string                `protobuf:"bytes,11,opt,name=client_platform,json=clientPlatform" json:"client_platform,omitempty"`
	Metadata       []*MetadataKV          `protobuf:"bytes,15,rep,name=metadata" json:"metadata,omitempty"`
	FinalFlag      *uint64                `protobuf:"varint,18,opt,name=final_flag,json=finalFlag" json:"final_flag,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *InboxRequest) Reset() {
	*x = InboxRequest{}
	mi := &file_tiktok_im_v1_im_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InboxRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InboxRequest) ProtoMessage() {}

func (x *InboxRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tiktok_im_v1_im_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InboxRequest.ProtoReflect.Descriptor instead.
func (*InboxRequest) Descriptor() ([]byte, []int) {
	return file_tiktok_im_v1_im_proto_rawDescGZIP(), []int{3}
}

func (x *InboxRequest) GetMessageType() uint64 {
	if x != nil && x.MessageType != nil {
		return *x.MessageType
	}
	return 0
}

func (x *InboxRequest) GetSubCommand() uint64 {
	if x != nil && x.SubCommand != nil {
		return *x.SubCommand
	}
	return 0
}

func (x *InboxRequest) GetClientVersion() string {
	if x != nil && x.ClientVersion != nil {
		return *x.ClientVersion
	}
	return ""
}

func (x *InboxRequest) GetOptions() *EmptyMessage {
	if x != nil {
		return x.Options
	}
	return nil
}

func (x *InboxRequest) GetPlatformFlag() uint64 {
	if x != nil && x.PlatformFlag != nil {
		return *x.PlatformFlag
	}
	return 0
}

func (x *InboxRequest) GetReserved_6() uint64 {
	if x != nil && x.Reserved_6 != nil {
		return *x.Reserved_6
	}
	return 0
}

func (x *InboxRequest) GetGitHash() string {
	if x != nil && x.GitHash != nil {
		return *x.GitHash
	}
	return ""
}

func (x *InboxRequest) GetPayload() *InboxRequestPayload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *InboxRequest) GetDeviceId() string {
	if x != nil && x.DeviceId != nil {
		return *x.DeviceId
	}
	return ""
}

func (x *InboxRequest) GetClientPlatform() string {
	if x != nil && x.ClientPlatform != nil {
		return *x.ClientPlatform
	}
	return ""
}

func (x *InboxRequest) GetMetadata() []*MetadataKV {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *InboxRequest) GetFinalFlag() uint64 {
	if x != nil && x.FinalFlag != nil {
		return *x.FinalFlag
	}
	return 0
}

type InboxRequestPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserInitList  *InboxInitRequest      `protobuf:"bytes,203,opt,name=user_init_list,json=userInitList" json:"user_init_list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InboxRequestPayload) Reset() {
	*x = InboxRequestPayload{}
	mi := &file_tiktok_im_v1_im_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InboxRequestPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InboxRequestPayload) ProtoMessage() {}

func (x *InboxRequestPayload) ProtoReflect() protoreflect.Message {
	mi := &file_tiktok_im_v1_im_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InboxRequestPayload.ProtoReflect.Descriptor instead.
func (*InboxRequestPayload) Descriptor() ([]byte, []int) {
	return file_tiktok_im_v1_im_proto_rawDescGZIP(), []int{4}
}

func (x *InboxRequestPayload) GetUserInitList() *InboxInitRequest {
	if x != nil {
		return x.UserInitList
	}
	return nil
}

type InboxInitRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reserved_1    *uint64                `protobuf:"varint,1,opt,name=reserved_1,json=reserved1" json:"reserved_1,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InboxInitRequest) Reset() {
	*x = InboxInitRequest{}
	mi := &file_tiktok_im_v1_im_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InboxInitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InboxInitRequest) ProtoMessage() {}

func (x *InboxInitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tiktok_im_v1_im_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InboxInitRequest.ProtoReflect.Descriptor instead.
func (*InboxInitRequest) Descriptor() ([]byte, []int) {
	return file_tiktok_im_v1_im_proto_rawDescGZIP(), []int{5}
}

func (x *InboxInitRequest) GetReserved_1() uint64 {
	if x != nil && x.Reserved_1 != nil {
		return *x.Reserved_1
	}
	return 0
}

type InboxResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        *uint64                `protobuf:"varint,1,opt,name=status" json:"status,omitempty"`
	Payload       *InboxResponsePayload  `protobuf:"bytes,6,opt,name=payload" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InboxResponse) Reset() {
	*x = InboxResponse{}
	mi := &file_tiktok_im_v1_im_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InboxResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InboxResponse) ProtoMessage() {}

func (x *InboxResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tiktok_im_v1_im_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InboxResponse.ProtoReflect.Descriptor instead.
func (*InboxResponse) Descriptor() ([]byte, []int) {
	return file_tiktok_im_v1_im_proto_rawDescGZIP(), []int{6}
}

func (x *InboxResponse) GetStatus() uint64 {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return 0
}

func (x *InboxResponse) GetPayload() *InboxResponsePayload {
	if x != nil {
		return x.Payload
	}
	return nil
}

type InboxResponsePayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserInitList  *InboxConversationList `protobuf:"bytes,203,opt,name=user_init_list,json=userInitList" json:"user_init_list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InboxResponsePayload) Reset() {
	*x = InboxResponsePayload{}
	mi := &file_tiktok_im_v1_im_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InboxResponsePayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InboxResponsePayload) ProtoMessage() {}

func (x *InboxResponsePayload) ProtoReflect() protoreflect.Message {
	mi := &file_tiktok_im_v1_im_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InboxResponsePayload.ProtoReflect.Descriptor instead.
func (*InboxResponsePayload) Descriptor() ([]byte, []int) {
	return file_tiktok_im_v1_im_proto_rawDescGZIP(), []int{7}
}

func (x *InboxResponsePayload) GetUserInitList() *InboxConversationList {
	if x != nil {
		return x.UserInitList
	}
	return nil
}

type InboxConversationList struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	Entries       []*InboxConversationEntry `protobuf:"bytes,1,rep,name=entries" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InboxConversationList) Reset() {
	*x = InboxConversationList{}
	mi := &file_tiktok_im_v1_im_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InboxConversationList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InboxConversationList) ProtoMessage() {}

func (x *InboxConversationList) ProtoReflect() protoreflect.Message {
	mi := &file_tiktok_im_v1_im_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InboxConversationList.ProtoReflect.Descriptor instead.
func (*InboxConversationList) Descriptor() ([]byte, []int) {
	return file_tiktok_im_v1_im_proto_rawDescGZIP(), []int{8}
}

func (x *InboxConversationList) GetEntries() []*InboxConversationEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

type InboxConversationEntry struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	ConversationId     *string                `protobuf:"bytes,1,opt,name=conversation_id,json=conversationId" json:"conversation_id,omitempty"`
	LastMessageType    *uint64                `protobuf:"varint,4,opt,name=last_message_type,json=lastMessageType" json:"last_message_type,omitempty"`
	SourceId           *uint64                `protobuf:"varint,5,opt,name=source_id,json=sourceId" json:"source_id,omitempty"`
	LastMessagePreview []byte                 `protobuf:"bytes,8,opt,name=last_message_preview,json=lastMessagePreview" json:"last_message_preview,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *InboxConversationEntry) Reset() {
	*x = InboxConversationEntry{}
	mi := &file_tiktok_im_v1_im_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InboxConversationEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InboxConversationEntry) ProtoMessage() {}

func (x *InboxConversationEntry) ProtoReflect() protoreflect.Message {
	mi := &file_tiktok_im_v1_im_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InboxConversationEntry.ProtoReflect.Descriptor instead.
func (*InboxConversationEntry) Descriptor() ([]byte, []int) {
	return file_tiktok_im_v1_im_proto_rawDescGZIP(), []int{9}
}

func (x *InboxConversationEntry) GetConversationId() string {
	if x != nil && x.ConversationId != nil {
		return *x.ConversationId
	}
	return ""
}

func (x *InboxConversationEntry) GetLastMessageType() uint64 {
	if x != nil && x.LastMessageType != nil {
		return *x.LastMessageType
	}
	return 0
}

func (x *InboxConversationEntry) GetSourceId() uint64 {
	if x != nil && x.SourceId != nil {
		return *x.SourceId
	}
	return 0
}

func (x *InboxConversationEntry) GetLastMessagePreview() []byte {
	if x != nil {
		return x.LastMessagePreview
	}
	return nil
}

type GetByConversationRequest struct {
	state          protoimpl.MessageState           `protogen:"open.v1"`
	MessageType    *uint64                          `protobuf:"varint,1,opt,name=message_type,json=messageType" json:"message_type,omitempty"`
	SubCommand     *uint64                          `protobuf:"varint,2,opt,name=sub_command,json=subCommand" json:"sub_command,omitempty"`
	ClientVersion  *string                          `protobuf:"bytes,3,opt,name=client_version,json=clientVersion" json:"client_version,omitempty"`
	Options        *EmptyMessage                    `protobuf:"bytes,4,opt,name=options" json:"options,omitempty"`
	PlatformFlag   *uint64                          `protobuf:"varint,5,opt,name=platform_flag,json=platformFlag" json:"platform_flag,omitempty"`
	Reserved_6     *uint64                          `protobuf:"varint,6,opt,name=reserved_6,json=reserved6" json:"reserved_6,omitempty"`
	GitHash        *string                          `protobuf:"bytes,7,opt,name=git_hash,json=gitHash" json:"git_hash,omitempty"`
	Payload        *GetByConversationRequestPayload `protobuf:"bytes,8,opt,name=payload" json:"payload,omitempty"`
	ClientPlatform *string                          `protobuf:"bytes,11,opt,name=client_platform,json=clientPlatform" json:"client_platform,omitempty"`
	Metadata       []*MetadataKV                    `protobuf:"bytes,15,rep,name=metadata" json:"metadata,omitempty"`
	FinalFlag      *uint64                          `protobuf:"varint,18,opt,name=final_flag,json=finalFlag" json:"final_flag,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetByConversationRequest) Reset() {
	*x = GetByConversationRequest{}
	mi := &file_tiktok_im_v1_im_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetByConversationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetByConversationRequest) ProtoMessage() {}

func (x *GetByConversationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tiktok_im_v1_im_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetByConversationRequest.ProtoReflect.Descriptor instead.
func (*GetByConversationRequest) Descriptor() ([]byte, []int) {
	return file_tiktok_im_v1_im_proto_rawDescGZIP(), []int{10}
}

func (x *GetByConversationRequest) GetMessageType() uint64 {
	if x != nil && x.MessageType != nil {
		return *x.MessageType
	}
	return 0
}

func (x *GetByConversationRequest) GetSubCommand() uint64 {
	if x != nil && x.SubCommand != nil {
		return *x.SubCommand
	}
	return 0
}

func (x *GetByConversationRequest) GetClientVersion() string {
	if x != nil && x.ClientVersion != nil {
		return *x.ClientVersion
	}
	return ""
}

func (x *GetByConversationRequest) GetOptions() *EmptyMessage {
	if x != nil {
		return x.Options
	}
	return nil
}

func (x *GetByConversationRequest) GetPlatformFlag() uint64 {
	if x != nil && x.PlatformFlag != nil {
		return *x.PlatformFlag
	}
	return 0
}

func (x *GetByConversationRequest) GetReserved_6() uint64 {
	if x != nil && x.Reserved_6 != nil {
		return *x.Reserved_6
	}
	return 0
}

func (x *GetByConversationRequest) GetGitHash() string {
	if x != nil && x.GitHash != nil {
		return *x.GitHash
	}
	return ""
}

func (x *GetByConversationRequest) GetPayload() *GetByConversationRequestPayload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *GetByConversationRequest) GetClientPlatform() string {
	if x != nil && x.ClientPlatform != nil {
		return *x.ClientPlatform
	}
	return ""
}

func (x *GetByConversationRequest) GetMetadata() []*MetadataKV {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *GetByConversationRequest) GetFinalFlag() uint64 {
	if x != nil && x.FinalFlag != nil {
		return *x.FinalFlag
	}
	return 0
}

type GetByConversationRequestPayload struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Query         *GetByConversationQuery `protobuf:"bytes,301,opt,name=query" json:"query,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetByConversationRequestPayload) Reset() {
	*x = GetByConversationRequestPayload{}
	mi := &file_tiktok_im_v1_im_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetByConversationRequestPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetByConversationRequestPayload) ProtoMessage() {}

func (x *GetByConversationRequestPayload) ProtoReflect() protoreflect.Message {
	mi := &file_tiktok_im_v1_im_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetByConversationRequestPayload.ProtoReflect.Descriptor instead.
func (*GetByConversationRequestPayload) Descriptor() ([]byte, []int) {
	return file_tiktok_im_v1_im_proto_rawDescGZIP(), []int{11}
}

func (x *GetByConversationRequestPayload) GetQuery() *GetByConversationQuery {
	if x != nil {
		return x.Query
	}
	return nil
}

type GetByConversationQuery struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ConversationId *string                `protobuf:"bytes,1,opt,name=conversation_id,json=conversationId" json:"conversation_id,omitempty"`
	Direction      *uint64                `protobuf:"varint,2,opt,name=direction" json:"direction,omitempty"`
	SourceId       *uint64                `protobuf:"varint,3,opt,name=source_id,json=sourceId" json:"source_id,omitempty"`
	Reserved_4     *uint64                `protobuf:"varint,4,opt,name=reserved_4,json=reserved4" json:"reserved_4,omitempty"`
	CursorTsUs     *uint64                `protobuf:"varint,5,opt,name=cursor_ts_us,json=cursorTsUs" json:"cursor_ts_us,omitempty"`
	Count          *uint64                `protobuf:"varint,6,opt,name=count" json:"count,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetByConversationQuery) Reset() {
	*x = GetByConversationQuery{}
	mi := &file_tiktok_im_v1_im_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetByConversationQuery) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetByConversationQuery) ProtoMessage() {}

func (x *GetByConversationQuery) ProtoReflect() protoreflect.Message {
	mi := &file_tiktok_im_v1_im_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetByConversationQuery.ProtoReflect.Descriptor instead.
func (*GetByConversationQuery) Descriptor() ([]byte, []int) {
	return file_tiktok_im_v1_im_proto_rawDescGZIP(), []int{12}
}

func (x *GetByConversationQuery) GetConversationId() string {
	if x != nil && x.ConversationId != nil {
		return *x.ConversationId
	}
	return ""
}

func (x *GetByConversationQuery) GetDirection() uint64 {
	if x != nil && x.Direction != nil {
		return *x.Direction
	}
	return 0
}

func (x *GetByConversationQuery) GetSourceId() uint64 {
	if x != nil && x.SourceId != nil {
		return *x.SourceId
	}
	return 0
}

func (x *GetByConversationQuery) GetReserved_4() uint64 {
	if x != nil && x.Reserved_4 != nil {
		return *x.Reserved_4
	}
	return 0
}

func (x *GetByConversationQuery) GetCursorTsUs() uint64 {
	if x != nil && x.CursorTsUs != nil {
		return *x.CursorTsUs
	}
	return 0
}

func (x *GetByConversationQuery) GetCount() uint64 {
	if x != nil && x.Count != nil {
		return *x.Count
	}
	return 0
}

type GetByConversationResponse struct {
	state         protoimpl.MessageState            `protogen:"open.v1"`
	Status        *uint64                           `protobuf:"varint,1,opt,name=status" json:"status,omitempty"`
	Payload       *GetByConversationResponsePayload `protobuf:"bytes,6,opt,name=payload" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetByConversationResponse) Reset() {
	*x = GetByConversationResponse{}
	mi := &file_tiktok_im_v1_im_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetByConversationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetByConversationResponse) ProtoMessage() {}

func (x *GetByConversationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tiktok_im_v1_im_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetByConversationResponse.ProtoReflect.Descriptor instead.
func (*GetByConversationResponse) Descriptor() ([]byte, []int) {
	return file_tiktok_im_v1_im_proto_rawDescGZIP(), []int{13}
}

func (x *GetByConversationResponse) GetStatus() uint64 {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return 0
}

func (x *GetByConversationResponse) GetPayload() *GetByConversationResponsePayload {
	if x != nil {
		return x.Payload
	}
	return nil
}

type GetByConversationResponsePayload struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Conversation  *ConversationMessageList `protobuf:"bytes,301,opt,name=conversation" json:"conversation,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetByConversationResponsePayload) Reset() {
	*x = GetByConversationResponsePayload{}
	mi := &file_tiktok_im_v1_im_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetByConversationResponsePayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetByConversationResponsePayload) ProtoMessage() {}

func (x *GetByConversationResponsePayload) ProtoReflect() protoreflect.Message {
	mi := &file_tiktok_im_v1_im_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetByConversationResponsePayload.ProtoReflect.Descriptor instead.
func (*GetByConversationResponsePayload) Descriptor() ([]byte, []int) {
	return file_tiktok_im_v1_im_proto_rawDescGZIP(), []int{14}
}

func (x *GetByConversationResponsePayload) GetConversation() *ConversationMessageList {
	if x != nil {
		return x.Conversation
	}
	return nil
}

type ConversationMessageList struct {
	state         protoimpl.MessageState      `protogen:"open.v1"`
	Entries       []*ConversationMessageEntry `protobuf:"bytes,1,rep,name=entries" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConversationMessageList) Reset() {
	*x = ConversationMessageList{}
	mi := &file_tiktok_im_v1_im_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConversationMessageList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConversationMessageList) ProtoMessage() {}

func (x *ConversationMessageList) ProtoReflect() protoreflect.Message {
	mi := &file_tiktok_im_v1_im_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConversationMessageList.ProtoReflect.Descriptor instead.
func (*ConversationMessageList) Descriptor() ([]byte, []int) {
	return file_tiktok_im_v1_im_proto_rawDescGZIP(), []int{15}
}

func (x *ConversationMessageList) GetEntries() []*ConversationMessageEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

type ConversationMessageEntry struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ConversationId  *string                `protobuf:"bytes,1,opt,name=conversation_id,json=conversationId" json:"conversation_id,omitempty"`
	ServerMessageId *uint64                `protobuf:"varint,3,opt,name=server_message_id,json=serverMessageId" json:"server_message_id,omitempty"`
	TimestampUs     *uint64                `protobuf:"varint,4,opt,name=timestamp_us,json=timestampUs" json:"timestamp_us,omitempty"`
	SenderUserId    *uint64                `protobuf:"varint,7,opt,name=sender_user_id,json=senderUserId" json:"sender_user_id,omitempty"`
	ContentJson     []byte                 `protobuf:"bytes,8,opt,name=content_json,json=contentJson" json:"content_json,omitempty"`
	Tags            []*MetadataTag         `protobuf:"bytes,9,rep,name=tags" json:"tags,omitempty"`
	Reactions       []*ReactionSummary     `protobuf:"bytes,15,rep,name=reactions" json:"reactions,omitempty"`
	CursorTsUs      *uint64                `protobuf:"varint,25,opt,name=cursor_ts_us,json=cursorTsUs" json:"cursor_ts_us,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ConversationMessageEntry) Reset() {
	*x = ConversationMessageEntry{}
	mi := &file_tiktok_im_v1_im_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConversationMessageEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConversationMessageEntry) ProtoMessage() {}

func (x *ConversationMessageEntry) ProtoReflect() protoreflect.Message {
	mi := &file_tiktok_im_v1_im_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConversationMessageEntry.ProtoReflect.Descriptor instead.
func (*ConversationMessageEntry) Descriptor() ([]byte, []int) {
	return file_tiktok_im_v1_im_proto_rawDescGZIP(), []int{16}
}

func (x *ConversationMessageEntry) GetConversationId() string {
	if x != nil && x.ConversationId != nil {
		return *x.ConversationId
	}
	return ""
}

func (x *ConversationMessageEntry) GetServerMessageId() uint64 {
	if x != nil && x.ServerMessageId != nil {
		return *x.ServerMessageId
	}
	return 0
}

func (x *ConversationMessageEntry) GetTimestampUs() uint64 {
	if x != nil && x.TimestampUs != nil {
		return *x.TimestampUs
	}
	return 0
}

func (x *ConversationMessageEntry) GetSenderUserId() uint64 {
	if x != nil && x.SenderUserId != nil {
		return *x.SenderUserId
	}
	return 0
}

func (x *ConversationMessageEntry) GetContentJson() []byte {
	if x != nil {
		return x.ContentJson
	}
	return nil
}

func (x *ConversationMessageEntry) GetTags() []*MetadataTag {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *ConversationMessageEntry) GetReactions() []*ReactionSummary {
	if x != nil {
		return x.Reactions
	}
	return nil
}

func (x *ConversationMessageEntry) GetCursorTsUs() uint64 {
	if x != nil && x.CursorTsUs != nil {
		return *x.CursorTsUs
	}
	return 0
}

type SendRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	MessageType    *uint64                `protobuf:"varint,1,opt,name=message_type,json=messageType" json:"message_type,omitempty"`
	SubCommand     *uint64                `protobuf:"varint,2,opt,name=sub_command,json=subCommand" json:"sub_command,omitempty"`
	ClientVersion  *string                `protobuf:"bytes,3,opt,name=client_version,json=clientVersion" json:"client_version,omitempty"`
	Options        *EmptyMessage          `protobuf:"bytes,4,opt,name=options" json:"options,omitempty"`
	PlatformFlag   *uint64                `protobuf:"varint,5,opt,name=platform_flag,json=platformFlag" json:"platform_flag,omitempty"`
	Reserved_6     *uint64                `protobuf:"varint,6,opt,name=reserved_6,json=reserved6" json:"reserved_6,omitempty"`
	GitHash        *string                `protobuf:"bytes,7,opt,name=git_hash,json=gitHash" json:"git_hash,omitempty"`
	Payload        *SendRequestPayload    `protobuf:"bytes,8,opt,name=payload" json:"payload,omitempty"`
	DeviceId       *string                `protobuf:"bytes,9,opt,name=device_id,json=deviceId" json:"device_id,omitempty"`
	ClientPlatform *string                `protobuf:"bytes,11,opt,name=client_platform,json=clientPlatform" json:"client_platform,omitempty"`
	Metadata       []*MetadataKV          `protobuf:"bytes,15,rep,name=metadata" json:"metadata,omitempty"`
	FinalFlag      *uint64                `protobuf:"varint,18,opt,name=final_flag,json=finalFlag" json:"final_flag,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SendRequest) Reset() {
	*x = SendRequest{}
	mi := &file_tiktok_im_v1_im_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendRequest) ProtoMessage() {}

func (x *SendRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tiktok_im_v1_im_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendRequest.ProtoReflect.Descriptor instead.
func (*SendRequest) Descriptor() ([]byte, []int) {
	return file_tiktok_im_v1_im_proto_rawDescGZIP(), []int{17}
}

func (x *SendRequest) GetMessageType() uint64 {
	if x != nil && x.MessageType != nil {
		return *x.MessageType
	}
	return 0
}

func (x *SendRequest) GetSubCommand() uint64 {
	if x != nil && x.SubCommand != nil {
		return *x.SubCommand
	}
	return 0
}

func (x *SendRequest) GetClientVersion() string {
	if x != nil && x.ClientVersion != nil {
		return *x.ClientVersion
	}
	return ""
}

func (x *SendRequest) GetOptions() *EmptyMessage {
	if x != nil {
		return x.Options
	}
	return nil
}

func (x *SendRequest) GetPlatformFlag() uint64 {
	if x != nil && x.PlatformFlag != nil {
		return *x.PlatformFlag
	}
	return 0
}

func (x *SendRequest) GetReserved_6() uint64 {
	if x != nil && x.Reserved_6 != nil {
		return *x.Reserved_6
	}
	return 0
}

func (x *SendRequest) GetGitHash() string {
	if x != nil && x.GitHash != nil {
		return *x.GitHash
	}
	return ""
}

func (x *SendRequest) GetPayload() *SendRequestPayload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *SendRequest) GetDeviceId() string {
	if x != nil && x.DeviceId != nil {
		return *x.DeviceId
	}
	return ""
}

func (x *SendRequest) GetClientPlatform() string {
	if x != nil && x.ClientPlatform != nil {
		return *x.ClientPlatform
	}
	return ""
}

func (x *SendRequest) GetMetadata() []*MetadataKV {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *SendRequest) GetFinalFlag() uint64 {
	if x != nil && x.FinalFlag != nil {
		return *x.FinalFlag
	}
	return 0
}

type SendRequestPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Send          *SendMessageBody       `protobuf:"bytes,100,opt,name=send" json:"send,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendRequestPayload) Reset() {
	*x = SendRequestPayload{}
	mi := &file_tiktok_im_v1_im_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendRequestPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendRequestPayload) ProtoMessage() {}

func (x *SendRequestPayload) ProtoReflect() protoreflect.Message {
	mi := &file_tiktok_im_v1_im_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendRequestPayload.ProtoReflect.Descriptor instead.
func (*SendRequestPayload) Descriptor() ([]byte, []int) {
	return file_tiktok_im_v1_im_proto_rawDescGZIP(), []int{18}
}

func (x *SendRequestPayload) GetSend() *SendMessageBody {
	if x != nil {
		return x.Send
	}
	return nil
}

type SendMessageBody struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ConversationId  *string                `protobuf:"bytes,1,opt,name=conversation_id,json=conversationId" json:"conversation_id,omitempty"`
	MessageKind     *uint64                `protobuf:"varint,2,opt,name=message_kind,json=messageKind" json:"message_kind,omitempty"`
	Reserved_3      *uint64                `protobuf:"varint,3,opt,name=reserved_3,json=reserved3" json:"reserved_3,omitempty"`
	ContentJson     []byte                 `protobuf:"bytes,4,opt,name=content_json,json=contentJson" json:"content_json,omitempty"`
	Tags            []*MetadataTag         `protobuf:"bytes,5,rep,name=tags" json:"tags,omitempty"`
	Reserved_6      *uint64                `protobuf:"varint,6,opt,name=reserved_6,json=reserved6" json:"reserved_6,omitempty"`
	Deprecated      *string                `protobuf:"bytes,7,opt,name=deprecated" json:"deprecated,omitempty"`
	ClientMessageId *string                `protobuf:"bytes,8,opt,name=client_message_id,json=clientMessageId" json:"client_message_id,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *SendMessageBody) Reset() {
	*x = SendMessageBody{}
	mi := &file_tiktok_im_v1_im_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendMessageBody) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendMessageBody) ProtoMessage() {}

func (x *SendMessageBody) ProtoReflect() protoreflect.Message {
	mi := &file_tiktok_im_v1_im_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendMessageBody.ProtoReflect.Descriptor instead.
func (*SendMessageBody) Descriptor() ([]byte, []int) {
	return file_tiktok_im_v1_im_proto_rawDescGZIP(), []int{19}
}

func (x *SendMessageBody) GetConversationId() string {
	if x != nil && x.ConversationId != nil {
		return *x.ConversationId
	}
	return ""
}

func (x *SendMessageBody) GetMessageKind() uint64 {
	if x != nil && x.MessageKind != nil {
		return *x.MessageKind
	}
	return 0
}

func (x *SendMessageBody) GetReserved_3() uint64 {
	if x != nil && x.Reserved_3 != nil {
		return *x.Reserved_3
	}
	return 0
}

func (x *SendMessageBody) GetContentJson() []byte {
	if x != nil {
		return x.ContentJson
	}
	return nil
}

func (x *SendMessageBody) GetTags() []*MetadataTag {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *SendMessageBody) GetReserved_6() uint64 {
	if x != nil && x.Reserved_6 != nil {
		return *x.Reserved_6
	}
	return 0
}

func (x *SendMessageBody) GetDeprecated() string {
	if x != nil && x.Deprecated != nil {
		return *x.Deprecated
	}
	return ""
}

func (x *SendMessageBody) GetClientMessageId() string {
	if x != nil && x.ClientMessageId != nil {
		return *x.ClientMessageId
	}
	return ""
}

type SendResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        *uint64                `protobuf:"varint,1,opt,name=status" json:"status,omitempty"`
	Primary       *SendResponsePayload   `protobuf:"bytes,6,opt,name=primary" json:"primary,omitempty"`
	Fallback      *SendResponsePayload   `protobuf:"bytes,8,opt,name=fallback" json:"fallback,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendResponse) Reset() {
	*x = SendResponse{}
	mi := &file_tiktok_im_v1_im_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendResponse) ProtoMessage() {}

func (x *SendResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tiktok_im_v1_im_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendResponse.ProtoReflect.Descriptor instead.
func (*SendResponse) Descriptor() ([]byte, []int) {
	return file_tiktok_im_v1_im_proto_rawDescGZIP(), []int{20}
}

func (x *SendResponse) GetStatus() uint64 {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return 0
}

func (x *SendResponse) GetPrimary() *SendResponsePayload {
	if x != nil {
		return x.Primary
	}
	return nil
}

func (x *SendResponse) GetFallback() *SendResponsePayload {
	if x != nil {
		return x.Fallback
	}
	return nil
}

type SendResponsePayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Send          *SendResponseBody      `protobuf:"bytes,100,opt,name=send" json:"send,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendResponsePayload) Reset() {
	*x = SendResponsePayload{}
	mi := &file_tiktok_im_v1_im_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendResponsePayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendResponsePayload) ProtoMessage() {}

func (x *SendResponsePayload) ProtoReflect() protoreflect.Message {
	mi := &file_tiktok_im_v1_im_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendResponsePayload.ProtoReflect.Descriptor instead.
func (*SendResponsePayload) Descriptor() ([]byte, []int) {
	return file_tiktok_im_v1_im_proto_rawDescGZIP(), []int{21}
}

func (x *SendResponsePayload) GetSend() *SendResponseBody {
	if x != nil {
		return x.Send
	}
	return nil
}

type SendResponseBody struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MessageId     *string                `protobuf:"bytes,1,opt,name=message_id,json=messageId" json:"message_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendResponseBody) Reset() {
	*x = SendResponseBody{}
	mi := &file_tiktok_im_v1_im_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendResponseBody) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendResponseBody) ProtoMessage() {}

func (x *SendResponseBody) ProtoReflect() protoreflect.Message {
	mi := &file_tiktok_im_v1_im_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendResponseBody.ProtoReflect.Descriptor instead.
func (*SendResponseBody) Descriptor() ([]byte, []int) {
	return file_tiktok_im_v1_im_proto_rawDescGZIP(), []int{22}
}

func (x *SendResponseBody) GetMessageId() string {
	if x != nil && x.MessageId != nil {
		return *x.MessageId
	}
	return ""
}

type ReactionRequest struct {
	state          protoimpl.MessageState  `protogen:"open.v1"`
	MessageType    *uint64                 `protobuf:"varint,1,opt,name=message_type,json=messageType" json:"message_type,omitempty"`
	SubCommand     *uint64                 `protobuf:"varint,2,opt,name=sub_command,json=subCommand" json:"sub_command,omitempty"`
	ClientVersion  *string                 `protobuf:"bytes,3,opt,name=client_version,json=clientVersion" json:"client_version,omitempty"`
	Options        *EmptyMessage           `protobuf:"bytes,4,opt,name=options" json:"options,omitempty"`
	PlatformFlag   *uint64                 `protobuf:"varint,5,opt,name=platform_flag,json=platformFlag" json:"platform_flag,omitempty"`
	Reserved_6     *uint64                 `protobuf:"varint,6,opt,name=reserved_6,json=reserved6" json:"reserved_6,omitempty"`
	GitHash        *string                 `protobuf:"bytes,7,opt,name=git_hash,json=gitHash" json:"git_hash,omitempty"`
	Payload        *ReactionRequestPayload `protobuf:"bytes,8,opt,name=payload" json:"payload,omitempty"`
	DeviceId       *string                 `protobuf:"bytes,9,opt,name=device_id,json=deviceId" json:"device_id,omitempty"`
	ClientPlatform *string                 `protobuf:"bytes,11,opt,name=client_platform,json=clientPlatform" json:"client_platform,omitempty"`
	Metadata       []*MetadataKV           `protobuf:"bytes,15,rep,name=metadata" json:"metadata,omitempty"`
	FinalFlag      *uint64                 `protobuf:"varint,18,opt,name=final_flag,json=finalFlag" json:"final_flag,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ReactionRequest) Reset() {
	*x = ReactionRequest{}
	mi := &file_tiktok_im_v1_im_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReactionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReactionRequest) ProtoMessage() {}

func (x *ReactionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tiktok_im_v1_im_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReactionRequest.ProtoReflect.Descriptor instead.
func (*ReactionRequest) Descriptor() ([]byte, []int) {
	return file_tiktok_im_v1_im_proto_rawDescGZIP(), []int{23}
}

func (x *ReactionRequest) GetMessageType() uint64 {
	if x != nil && x.MessageType != nil {
		return *x.MessageType
	}
	return 0
}

func (x *ReactionRequest) GetSubCommand() uint64 {
	if x != nil && x.SubCommand != nil {
		return *x.SubCommand
	}
	return 0
}

func (x *ReactionRequest) GetClientVersion() string {
	if x != nil && x.ClientVersion != nil {
		return *x.ClientVersion
	}
	return ""
}

func (x *ReactionRequest) GetOptions() *EmptyMessage {
	if x != nil {
		return x.Options
	}
	return nil
}

func (x *ReactionRequest) GetPlatformFlag() uint64 {
	if x != nil && x.PlatformFlag != nil {
		return *x.PlatformFlag
	}
	return 0
}

func (x *ReactionRequest) GetReserved_6() uint64 {
	if x != nil && x.Reserved_6 != nil {
		return *x.Reserved_6
	}
	return 0
}

func (x *ReactionRequest) GetGitHash() string {
	if x != nil && x.GitHash != nil {
		return *x.GitHash
	}
	return ""
}

func (x *ReactionRequest) GetPayload() *ReactionRequestPayload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ReactionRequest) GetDeviceId() string {
	if x != nil && x.DeviceId != nil {
		return *x.DeviceId
	}
	return ""
}

func (x *ReactionRequest) GetClientPlatform() string {
	if x != nil && x.ClientPlatform != nil {
		return *x.ClientPlatform
	}
	return ""
}

func (x *ReactionRequest) GetMetadata() []*MetadataKV {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *ReactionRequest) GetFinalFlag() uint64 {
	if x != nil && x.FinalFlag != nil {
		return *x.FinalFlag
	}
	return 0
}

type ReactionRequestPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Wrapper       *ReactionWrapper       `protobuf:"bytes,705,opt,name=wrapper" json:"wrapper,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReactionRequestPayload) Reset() {
	*x = ReactionRequestPayload{}
	mi := &file_tiktok_im_v1_im_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReactionRequestPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReactionRequestPayload) ProtoMessage() {}

func (x *ReactionRequestPayload) ProtoReflect() protoreflect.Message {
	mi := &file_tiktok_im_v1_im_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReactionRequestPayload.ProtoReflect.Descriptor instead.
func (*ReactionRequestPayload) Descriptor() ([]byte, []int) {
	return file_tiktok_im_v1_im_proto_rawDescGZIP(), []int{24}
}

func (x *ReactionRequestPayload) GetWrapper() *ReactionWrapper {
	if x != nil {
		return x.Wrapper
	}
	return nil
}

type ReactionWrapper struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Body          *ReactionBody          `protobuf:"bytes,1,opt,name=body" json:"body,omitempty"`
	Deprecated    *string                `protobuf:"bytes,2,opt,name=deprecated" json:"deprecated,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReactionWrapper) Reset() {
	*x = ReactionWrapper{}
	mi := &file_tiktok_im_v1_im_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReactionWrapper) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReactionWrapper) ProtoMessage() {}

func (x *ReactionWrapper) ProtoReflect() protoreflect.Message {
	mi := &file_tiktok_im_v1_im_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReactionWrapper.ProtoReflect.Descriptor instead.
func (*ReactionWrapper) Descriptor() ([]byte, []int) {
	return file_tiktok_im_v1_im_proto_rawDescGZIP(), []int{25}
}

func (x *ReactionWrapper) GetBody() *ReactionBody {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *ReactionWrapper) GetDeprecated() string {
	if x != nil && x.Deprecated != nil {
		return *x.Deprecated
	}
	return ""
}

type ReactionBody struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ConversationId  *string                `protobuf:"bytes,1,opt,name=conversation_id,json=conversationId" json:"conversation_id,omitempty"`
	ActionFlag      *uint64                `protobuf:"varint,2,opt,name=action_flag,json=actionFlag" json:"action_flag,omitempty"`
	SourceId        *uint64                `protobuf:"varint,3,opt,name=source_id,json=sourceId" json:"source_id,omitempty"`
	ServerMessageId *uint64                `protobuf:"varint,4,opt,name=server_message_id,json=serverMessageId" json:"server_message_id,omitempty"`
	ClientMessageId *string                `protobuf:"bytes,5,opt,name=client_message_id,json=clientMessageId" json:"client_message_id,omitempty"`
	Reactions       []*ReactionMutation    `protobuf:"bytes,6,rep,name=reactions" json:"reactions,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ReactionBody) Reset() {
	*x = ReactionBody{}
	mi := &file_tiktok_im_v1_im_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReactionBody) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReactionBody) ProtoMessage() {}

func (x *ReactionBody) ProtoReflect() protoreflect.Message {
	mi := &file_tiktok_im_v1_im_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReactionBody.ProtoReflect.Descriptor instead.
func (*ReactionBody) Descriptor() ([]byte, []int) {
	return file_tiktok_im_v1_im_proto_rawDescGZIP(), []int{26}
}

func (x *ReactionBody) GetConversationId() string {
	if x != nil && x.ConversationId != nil {
		return *x.ConversationId
	}
	return ""
}

func (x *ReactionBody) GetActionFlag() uint64 {
	if x != nil && x.ActionFlag != nil {
		return *x.ActionFlag
	}
	return 0
}

func (x *ReactionBody) GetSourceId() uint64 {
	if x != nil && x.SourceId != nil {
		return *x.SourceId
	}
	return 0
}

func (x *ReactionBody) GetServerMessageId() uint64 {
	if x != nil && x.ServerMessageId != nil {
		return *x.ServerMessageId
	}
	return 0
}

func (x *ReactionBody) GetClientMessageId() string {
	if x != nil && x.ClientMessageId != nil {
		return *x.ClientMessageId
	}
	return ""
}

func (x *ReactionBody) GetReactions() []*ReactionMutation {
	if x != nil {
		return x.Reactions
	}
	return nil
}

type ReactionMutation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Action        *uint64                `protobuf:"varint,1,opt,name=action" json:"action,omitempty"`
	ReactionKey   *string                `protobuf:"bytes,2,opt,name=reaction_key,json=reactionKey" json:"reaction_key,omitempty"`
	SelfUserId    *string                `protobuf:"bytes,4,opt,name=self_user_id,json=selfUserId" json:"self_user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReactionMutation) Reset() {
	*x = ReactionMutation{}
	mi := &file_tiktok_im_v1_im_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReactionMutation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReactionMutation) ProtoMessage() {}

func (x *ReactionMutation) ProtoReflect() protoreflect.Message {
	mi := &file_tiktok_im_v1_im_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReactionMutation.ProtoReflect.Descriptor instead.
func (*ReactionMutation) Descriptor() ([]byte, []int) {
	return file_tiktok_im_v1_im_proto_rawDescGZIP(), []int{27}
}

func (x *ReactionMutation) GetAction() uint64 {
	if x != nil && x.Action != nil {
		return *x.Action
	}
	return 0
}

func (x *ReactionMutation) GetReactionKey() string {
	if x != nil && x.ReactionKey != nil {
		return *x.ReactionKey
	}
	return ""
}

func (x *ReactionMutation) GetSelfUserId() string {
	if x != nil && x.SelfUserId != nil {
		return *x.SelfUserId
	}
	return ""
}

type ReactionSummary struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReactionKey   *string                `protobuf:"bytes,1,opt,name=reaction_key,json=reactionKey" json:"reaction_key,omitempty"`
	Users         *ReactionUsers         `protobuf:"bytes,2,opt,name=users" json:"users,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReactionSummary) Reset() {
	*x = ReactionSummary{}
	mi := &file_tiktok_im_v1_im_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReactionSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReactionSummary) ProtoMessage() {}

func (x *ReactionSummary) ProtoReflect() protoreflect.Message {
	mi := &file_tiktok_im_v1_im_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReactionSummary.ProtoReflect.Descriptor instead.
func (*ReactionSummary) Descriptor() ([]byte, []int) {
	return file_tiktok_im_v1_im_proto_rawDescGZIP(), []int{28}
}

func (x *ReactionSummary) GetReactionKey() string {
	if x != nil && x.ReactionKey != nil {
		return *x.ReactionKey
	}
	return ""
}

func (x *ReactionSummary) GetUsers() *ReactionUsers {
	if x != nil {
		return x.Users
	}
	return nil
}

type ReactionUsers struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entries       []*ReactionUser        `protobuf:"bytes,1,rep,name=entries" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReactionUsers) Reset() {
	*x = ReactionUsers{}
	mi := &file_tiktok_im_v1_im_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReactionUsers) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReactionUsers) ProtoMessage() {}

func (x *ReactionUsers) ProtoReflect() protoreflect.Message {
	mi := &file_tiktok_im_v1_im_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReactionUsers.ProtoReflect.Descriptor instead.
func (*ReactionUsers) Descriptor() ([]byte, []int) {
	return file_tiktok_im_v1_im_proto_rawDescGZIP(), []int{29}
}

func (x *ReactionUsers) GetEntries() []*ReactionUser {
	if x != nil {
		return x.Entries
	}
	return nil
}

type ReactionUser struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        *uint64                `protobuf:"varint,1,opt,name=user_id,json=userId" json:"user_id,omitempty"`
	TimestampS    *uint64                `protobuf:"varint,3,opt,name=timestamp_s,json=timestampS" json:"timestamp_s,omitempty"`
	UserIdStr     *string                `protobuf:"bytes,4,opt,name=user_id_str,json=userIdStr" json:"user_id_str,omitempty"`
	TimestampUs   *uint64                `protobuf:"varint,6,opt,name=timestamp_us,json=timestampUs" json:"timestamp_us,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReactionUser) Reset() {
	*x = ReactionUser{}
	mi := &file_tiktok_im_v1_im_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReactionUser) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReactionUser) ProtoMessage() {}

func (x *ReactionUser) ProtoReflect() protoreflect.Message {
	mi := &file_tiktok_im_v1_im_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReactionUser.ProtoReflect.Descriptor instead.
func (*ReactionUser) Descriptor() ([]byte, []int) {
	return file_tiktok_im_v1_im_proto_rawDescGZIP(), []int{30}
}

func (x *ReactionUser) GetUserId() uint64 {
	if x != nil && x.UserId != nil {
		return *x.UserId
	}
	return 0
}

func (x *ReactionUser) GetTimestampS() uint64 {
	if x != nil && x.TimestampS != nil {
		return *x.TimestampS
	}
	return 0
}

func (x *ReactionUser) GetUserIdStr() string {
	if x != nil && x.UserIdStr != nil {
		return *x.UserIdStr
	}
	return ""
}

func (x *ReactionUser) GetTimestampUs() uint64 {
	if x != nil && x.TimestampUs != nil {
		return *x.TimestampUs
	}
	return 0
}

type WebsocketFrame struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Envelope      *WebsocketEnvelope     `protobuf:"bytes,8,opt,name=envelope" json:"envelope,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WebsocketFrame) Reset() {
	*x = WebsocketFrame{}
	mi := &file_tiktok_im_v1_im_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WebsocketFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WebsocketFrame) ProtoMessage() {}

func (x *WebsocketFrame) ProtoReflect() protoreflect.Message {
	mi := &file_tiktok_im_v1_im_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WebsocketFrame.ProtoReflect.Descriptor instead.
func (*WebsocketFrame) Descriptor() ([]byte, []int) {
	return file_tiktok_im_v1_im_proto_rawDescGZIP(), []int{31}
}

func (x *WebsocketFrame) GetEnvelope() *WebsocketEnvelope {
	if x != nil {
		return x.Envelope
	}
	return nil
}

type WebsocketEnvelope struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InnerType     *uint64                `protobuf:"varint,1,opt,name=inner_type,json=innerType" json:"inner_type,omitempty"`
	Commands      *WebsocketCommands     `protobuf:"bytes,6,opt,name=commands" json:"commands,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WebsocketEnvelope) Reset() {
	*x = WebsocketEnvelope{}
	mi := &file_tiktok_im_v1_im_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WebsocketEnvelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WebsocketEnvelope) ProtoMessage() {}

func (x *WebsocketEnvelope) ProtoReflect() protoreflect.Message {
	mi := &file_tiktok_im_v1_im_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WebsocketEnvelope.ProtoReflect.Descriptor instead.
func (*WebsocketEnvelope) Descriptor() ([]byte, []int) {
	return file_tiktok_im_v1_im_proto_rawDescGZIP(), []int{32}
}

func (x *WebsocketEnvelope) GetInnerType() uint64 {
	if x != nil && x.InnerType != nil {
		return *x.InnerType
	}
	return 0
}

func (x *WebsocketEnvelope) GetCommands() *WebsocketCommands {
	if x != nil {
		return x.Commands
	}
	return nil
}

type WebsocketCommands struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Chat          *WebsocketChat         `protobuf:"bytes,500,opt,name=chat" json:"chat,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WebsocketCommands) Reset() {
	*x = WebsocketCommands{}
	mi := &file_tiktok_im_v1_im_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WebsocketCommands) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WebsocketCommands) ProtoMessage() {}

func (x *WebsocketCommands) ProtoReflect() protoreflect.Message {
	mi := &file_tiktok_im_v1_im_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WebsocketCommands.ProtoReflect.Descriptor instead.
func (*WebsocketCommands) Descriptor() ([]byte, []int) {
	return file_tiktok_im_v1_im_proto_rawDescGZIP(), []int{33}
}

func (x *WebsocketCommands) GetChat() *WebsocketChat {
	if x != nil {
		return x.Chat
	}
	return nil
}

type WebsocketChat struct {
	state          protoimpl.MessageState  `protogen:"open.v1"`
	ConversationId *string                 `protobuf:"bytes,2,opt,name=conversation_id,json=conversationId" json:"conversation_id,omitempty"`
	Detail         *WebsocketMessageDetail `protobuf:"bytes,5,opt,name=detail" json:"detail,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *WebsocketChat) Reset() {
	*x = WebsocketChat{}
	mi := &file_tiktok_im_v1_im_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WebsocketChat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WebsocketChat) ProtoMessage() {}

func (x *WebsocketChat) ProtoReflect() protoreflect.Message {
	mi := &file_tiktok_im_v1_im_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WebsocketChat.ProtoReflect.Descriptor instead.
func (*WebsocketChat) Descriptor() ([]byte, []int) {
	return file_tiktok_im_v1_im_proto_rawDescGZIP(), []int{34}
}

func (x *WebsocketChat) GetConversationId() string {
	if x != nil && x.ConversationId != nil {
		return *x.ConversationId
	}
	return ""
}

func (x *WebsocketChat) GetDetail() *WebsocketMessageDetail {
	if x != nil {
		return x.Detail
	}
	return nil
}

type WebsocketMessageDetail struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ServerMessageId *uint64                `protobuf:"varint,3,opt,name=server_message_id,json=serverMessageId" json:"server_message_id,omitempty"`
	TimestampUs     *uint64                `protobuf:"varint,4,opt,name=timestamp_us,json=timestampUs" json:"timestamp_us,omitempty"`
	SenderUserId    *uint64                `protobuf:"varint,7,opt,name=sender_user_id,json=senderUserId" json:"sender_user_id,omitempty"`
	ContentJson     []byte                 `protobuf:"bytes,8,opt,name=content_json,json=contentJson" json:"content_json,omitempty"`
	Tags            []*MetadataTag         `protobuf:"bytes,9,rep,name=tags" json:"tags,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *WebsocketMessageDetail) Reset() {
	*x = WebsocketMessageDetail{}
	mi := &file_tiktok_im_v1_im_proto_msgTypes[35]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WebsocketMessageDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WebsocketMessageDetail) ProtoMessage() {}

func (x *WebsocketMessageDetail) ProtoReflect() protoreflect.Message {
	mi := &file_tiktok_im_v1_im_proto_msgTypes[35]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WebsocketMessageDetail.ProtoReflect.Descriptor instead.
func (*WebsocketMessageDetail) Descriptor() ([]byte, []int) {
	return file_tiktok_im_v1_im_proto_rawDescGZIP(), []int{35}
}

func (x *WebsocketMessageDetail) GetServerMessageId() uint64 {
	if x != nil && x.ServerMessageId != nil {
		return *x.ServerMessageId
	}
	return 0
}

func (x *WebsocketMessageDetail) GetTimestampUs() uint64 {
	if x != nil && x.TimestampUs != nil {
		return *x.TimestampUs
	}
	return 0
}

func (x *WebsocketMessageDetail) GetSenderUserId() uint64 {
	if x != nil && x.SenderUserId != nil {
		return *x.SenderUserId
	}
	return 0
}

func (x *WebsocketMessageDetail) GetContentJson() []byte {
	if x != nil {
		return x.ContentJson
	}
	return nil
}

func (x *WebsocketMessageDetail) GetTags() []*MetadataTag {
	if x != nil {
		return x.Tags
	}
	return nil
}

var File_tiktok_im_v1_im_proto protoreflect.FileDescriptor

const file_tiktok_im_v1_im_proto_rawDesc = "" +
	"\n" +
	"\x15tiktok/im/v1/im.proto\x12\ftiktok.im.v1\"\x0e\n" +
	"\fEmptyMessage\"4\n" +
	"\n" +
	"MetadataKV\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\"5\n" +
	"\vMetadataTag\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value\"\xe6\x03\n" +
	"\fInboxRequest\x12!\n" +
	"\fmessage_type\x18\x01 \x01(\x04R\vmessageType\x12\x1f\n" +
	"\vsub_command\x18\x02 \x01(\x04R\n" +
	"subCommand\x12%\n" +
	"\x0eclient_version\x18\x03 \x01(\tR\rclientVersion\x124\n" +
	"\aoptions\x18\x04 \x01(\v2\x1a.tiktok.im.v1.EmptyMessageR\aoptions\x12#\n" +
	"\rplatform_flag\x18\x05 \x01(\x04R\fplatformFlag\x12\x1d\n" +
	"\n" +
	"reserved_6\x18\x06 \x01(\x04R\treserved6\x12\x19\n" +
	"\bgit_hash\x18\a \x01(\tR\agitHash\x12;\n" +
	"\apayload\x18\b \x01(\v2!.tiktok.im.v1.InboxRequestPayloadR\apayload\x12\x1b\n" +
	"\tdevice_id\x18\t \x01(\tR\bdeviceId\x12'\n" +
	"\x0fclient_platform\x18\v \x01(\tR\x0eclientPlatform\x124\n" +
	"\bmetadata\x18\x0f \x03(\v2\x18.tiktok.im.v1.MetadataKVR\bmetadata\x12\x1d\n" +
	"\n" +
	"final_flag\x18\x12 \x01(\x04R\tfinalFlag\"\\\n" +
	"\x13InboxRequestPayload\x12E\n" +
	"\x0euser_init_list\x18\xcb\x01 \x01(\v2\x1e.tiktok.im.v1.InboxInitRequestR\fuserInitList\"1\n" +
	"\x10InboxInitRequest\x12\x1d\n" +
	"\n" +
	"reserved_1\x18\x01 \x01(\x04R\treserved1\"e\n" +
	"\rInboxResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\x04R\x06status\x12<\n" +
	"\apayload\x18\x06 \x01(\v2\".tiktok.im.v1.InboxResponsePayloadR\apayload\"b\n" +
	"\x14InboxResponsePayload\x12J\n" +
	"\x0euser_init_list\x18\xcb\x01 \x01(\v2#.tiktok.im.v1.InboxConversationListR\fuserInitList\"W\n" +
	"\x15InboxConversationList\x12>\n" +
	"\aentries\x18\x01 \x03(\v2$.tiktok.im.v1.InboxConversationEntryR\aentries\"\xbc\x01\n" +
	"\x16InboxConversationEntry\x12'\n" +
	"\x0fconversation_id\x18\x01 \x01(\tR\x0econversationId\x12*\n" +
	"\x11last_message_type\x18\x04 \x01(\x04R\x0flastMessageType\x12\x1b\n" +
	"\tsource_id\x18\x05 \x01(\x04R\bsourceId\x120\n" +
	"\x14last_message_preview\x18\b \x01(\fR\x12lastMessagePreview\"\xe1\x03\n" +
	"\x18GetByConversationRequest\x12!\n" +
	"\fmessage_type\x18\x01 \x01(\x04R\vmessageType\x12\x1f\n" +
	"\vsub_command\x18\x02 \x01(\x04R\n" +
	"subCommand\x12%\n" +
	"\x0eclient_version\x18\x03 \x01(\tR\rclientVersion\x124\n" +
	"\aoptions\x18\x04 \x01(\v2\x1a.tiktok.im.v1.EmptyMessageR\aoptions\x12#\n" +
	"\rplatform_flag\x18\x05 \x01(\x04R\fplatformFlag\x12\x1d\n" +
	"\n" +
	"reserved_6\x18\x06 \x01(\x04R\treserved6\x12\x19\n" +
	"\bgit_hash\x18\a \x01(\tR\agitHash\x12G\n" +
	"\apayload\x18\b \x01(\v2-.tiktok.im.v1.GetByConversationRequestPayloadR\apayload\x12'\n" +
	"\x0fclient_platform\x18\v \x01(\tR\x0eclientPlatform\x124\n" +
	"\bmetadata\x18\x0f \x03(\v2\x18.tiktok.im.v1.MetadataKVR\bmetadata\x12\x1d\n" +
	"\n" +
	"final_flag\x18\x12 \x01(\x04R\tfinalFlag\"^\n" +
	"\x1fGetByConversationRequestPayload\x12;\n" +
	"\x05query\x18\xad\x02 \x01(\v2$.tiktok.im.v1.GetByConversationQueryR\x05query\"\xd3\x01\n" +
	"\x16GetByConversationQuery\x12'\n" +
	"\x0fconversation_id\x18\x01 \x01(\tR\x0econversationId\x12\x1c\n" +
	"\tdirection\x18\x02 \x01(\x04R\tdirection\x12\x1b\n" +
	"\tsource_id\x18\x03 \x01(\x04R\bsourceId\x12\x1d\n" +
	"\n" +
	"reserved_4\x18\x04 \x01(\x04R\treserved4\x12 \n" +
	"\fcursor_ts_us\x18\x05 \x01(\x04R\n" +
	"cursorTsUs\x12\x14\n" +
	"\x05count\x18\x06 \x01(\x04R\x05count\"}\n" +
	"\x19GetByConversationResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\x04R\x06status\x12H\n" +
	"\apayload\x18\x06 \x01(\v2..tiktok.im.v1.GetByConversationResponsePayloadR\apayload\"n\n" +
	" GetByConversationResponsePayload\x12J\n" +
	"\fconversation\x18\xad\x02 \x01(\v2%.tiktok.im.v1.ConversationMessageListR\fconversation\"[\n" +
	"\x17ConversationMessageList\x12@\n" +
	"\aentries\x18\x01 \x03(\v2&.tiktok.im.v1.ConversationMessageEntryR\aentries\"\xe9\x02\n" +
	"\x18ConversationMessageEntry\x12'\n" +
	"\x0fconversation_id\x18\x01 \x01(\tR\x0econversationId\x12*\n" +
	"\x11server_message_id\x18\x03 \x01(\x04R\x0fserverMessageId\x12!\n" +
	"\ftimestamp_us\x18\x04 \x01(\x04R\vtimestampUs\x12$\n" +
	"\x0esender_user_id\x18\a \x01(\x04R\fsenderUserId\x12!\n" +
	"\fcontent_json\x18\b \x01(\fR\vcontentJson\x12-\n" +
	"\x04tags\x18\t \x03(\v2\x19.tiktok.im.v1.MetadataTagR\x04tags\x12;\n" +
	"\treactions\x18\x0f \x03(\v2\x1d.tiktok.im.v1.ReactionSummaryR\treactions\x12 \n" +
	"\fcursor_ts_us\x18\x19 \x01(\x04R\n" +
	"cursorTsUs\"\xe4\x03\n" +
	"\vSendRequest\x12!\n" +
	"\fmessage_type\x18\x01 \x01(\x04R\vmessageType\x12\x1f\n" +
	"\vsub_command\x18\x02 \x01(\x04R\n" +
	"subCommand\x12%\n" +
	"\x0eclient_version\x18\x03 \x01(\tR\rclientVersion\x124\n" +
	"\aoptions\x18\x04 \x01(\v2\x1a.tiktok.im.v1.EmptyMessageR\aoptions\x12#\n" +
	"\rplatform_flag\x18\x05 \x01(\x04R\fplatformFlag\x12\x1d\n" +
	"\n" +
	"reserved_6\x18\x06 \x01(\x04R\treserved6\x12\x19\n" +
	"\bgit_hash\x18\a \x01(\tR\agitHash\x12:\n" +
	"\apayload\x18\b \x01(\v2 .tiktok.im.v1.SendRequestPayloadR\apayload\x12\x1b\n" +
	"\tdevice_id\x18\t \x01(\tR\bdeviceId\x12'\n" +
	"\x0fclient_platform\x18\v \x01(\tR\x0eclientPlatform\x124\n" +
	"\bmetadata\x18\x0f \x03(\v2\x18.tiktok.im.v1.MetadataKVR\bmetadata\x12\x1d\n" +
	"\n" +
	"final_flag\x18\x12 \x01(\x04R\tfinalFlag\"G\n" +
	"\x12SendRequestPayload\x121\n" +
	"\x04send\x18d \x01(\v2\x1d.tiktok.im.v1.SendMessageBodyR\x04send\"\xb9\x02\n" +
	"\x0fSendMessageBody\x12'\n" +
	"\x0fconversation_id\x18\x01 \x01(\tR\x0econversationId\x12!\n" +
	"\fmessage_kind\x18\x02 \x01(\x04R\vmessageKind\x12\x1d\n" +
	"\n" +
	"reserved_3\x18\x03 \x01(\x04R\treserved3\x12!\n" +
	"\fcontent_json\x18\x04 \x01(\fR\vcontentJson\x12-\n" +
	"\x04tags\x18\x05 \x03(\v2\x19.tiktok.im.v1.MetadataTagR\x04tags\x12\x1d\n" +
	"\n" +
	"reserved_6\x18\x06 \x01(\x04R\treserved6\x12\x1e\n" +
	"\n" +
	"deprecated\x18\a \x01(\tR\n" +
	"deprecated\x12*\n" +
	"\x11client_message_id\x18\b \x01(\tR\x0fclientMessageId\"\xa2\x01\n" +
	"\fSendResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\x04R\x06status\x12;\n" +
	"\aprimary\x18\x06 \x01(\v2!.tiktok.im.v1.SendResponsePayloadR\aprimary\x12=\n" +
	"\bfallback\x18\b \x01(\v2!.tiktok.im.v1.SendResponsePayloadR\bfallback\"I\n" +
	"\x13SendResponsePayload\x122\n" +
	"\x04send\x18d \x01(\v2\x1e.tiktok.im.v1.SendResponseBodyR\x04send\"1\n" +
	"\x10SendResponseBody\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\tR\tmessageId\"\xec\x03\n" +
	"\x0fReactionRequest\x12!\n" +
	"\fmessage_type\x18\x01 \x01(\x04R\vmessageType\x12\x1f\n" +
	"\vsub_command\x18\x02 \x01(\x04R\n" +
	"subCommand\x12%\n" +
	"\x0eclient_version\x18\x03 \x01(\tR\rclientVersion\x124\n" +
	"\aoptions\x18\x04 \x01(\v2\x1a.tiktok.im.v1.EmptyMessageR\aoptions\x12#\n" +
	"\rplatform_flag\x18\x05 \x01(\x04R\fplatformFlag\x12\x1d\n" +
	"\n" +
	"reserved_6\x18\x06 \x01(\x04R\treserved6\x12\x19\n" +
	"\bgit_hash\x18\a \x01(\tR\agitHash\x12>\n" +
	"\apayload\x18\b \x01(\v2$.tiktok.im.v1.ReactionRequestPayloadR\apayload\x12\x1b\n" +
	"\tdevice_id\x18\t \x01(\tR\bdeviceId\x12'\n" +
	"\x0fclient_platform\x18\v \x01(\tR\x0eclientPlatform\x124\n" +
	"\bmetadata\x18\x0f \x03(\v2\x18.tiktok.im.v1.MetadataKVR\bmetadata\x12\x1d\n" +
	"\n" +
	"final_flag\x18\x12 \x01(\x04R\tfinalFlag\"R\n" +
	"\x16ReactionRequestPayload\x128\n" +
	"\awrapper\x18\xc1\x05 \x01(\v2\x1d.tiktok.im.v1.ReactionWrapperR\awrapper\"a\n" +
	"\x0fReactionWrapper\x12.\n" +
	"\x04body\x18\x01 \x01(\v2\x1a.tiktok.im.v1.ReactionBodyR\x04body\x12\x1e\n" +
	"\n" +
	"deprecated\x18\x02 \x01(\tR\n" +
	"deprecated\"\x8b\x02\n" +
	"\fReactionBody\x12'\n" +
	"\x0fconversation_id\x18\x01 \x01(\tR\x0econversationId\x12\x1f\n" +
	"\vaction_flag\x18\x02 \x01(\x04R\n" +
	"actionFlag\x12\x1b\n" +
	"\tsource_id\x18\x03 \x01(\x04R\bsourceId\x12*\n" +
	"\x11server_message_id\x18\x04 \x01(\x04R\x0fserverMessageId\x12*\n" +
	"\x11client_message_id\x18\x05 \x01(\tR\x0fclientMessageId\x12<\n" +
	"\treactions\x18\x06 \x03(\v2\x1e.tiktok.im.v1.ReactionMutationR\treactions\"o\n" +
	"\x10ReactionMutation\x12\x16\n" +
	"\x06action\x18\x01 \x01(\x04R\x06action\x12!\n" +
	"\freaction_key\x18\x02 \x01(\tR\vreactionKey\x12 \n" +
	"\fself_user_id\x18\x04 \x01(\tR\n" +
	"selfUserId\"g\n" +
	"\x0fReactionSummary\x12!\n" +
	"\freaction_key\x18\x01 \x01(\tR\vreactionKey\x121\n" +
	"\x05users\x18\x02 \x01(\v2\x1b.tiktok.im.v1.ReactionUsersR\x05users\"E\n" +
	"\rReactionUsers\x124\n" +
	"\aentries\x18\x01 \x03(\v2\x1a.tiktok.im.v1.ReactionUserR\aentries\"\x8b\x01\n" +
	"\fReactionUser\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId\x12\x1f\n" +
	"\vtimestamp_s\x18\x03 \x01(\x04R\n" +
	"timestampS\x12\x1e\n" +
	"\vuser_id_str\x18\x04 \x01(\tR\tuserIdStr\x12!\n" +
	"\ftimestamp_us\x18\x06 \x01(\x04R\vtimestampUs\"M\n" +
	"\x0eWebsocketFrame\x12;\n" +
	"\benvelope\x18\b \x01(\v2\x1f.tiktok.im.v1.WebsocketEnvelopeR\benvelope\"o\n" +
	"\x11WebsocketEnvelope\x12\x1d\n" +
	"\n" +
	"inner_type\x18\x01 \x01(\x04R\tinnerType\x12;\n" +
	"\bcommands\x18\x06 \x01(\v2\x1f.tiktok.im.v1.WebsocketCommandsR\bcommands\"E\n" +
	"\x11WebsocketCommands\x120\n" +
	"\x04chat\x18\xf4\x03 \x01(\v2\x1b.tiktok.im.v1.WebsocketChatR\x04chat\"v\n" +
	"\rWebsocketChat\x12'\n" +
	"\x0fconversation_id\x18\x02 \x01(\tR\x0econversationId\x12<\n" +
	"\x06detail\x18\x05 \x01(\v2$.tiktok.im.v1.WebsocketMessageDetailR\x06detail\"\xdf\x01\n" +
	"\x16WebsocketMessageDetail\x12*\n" +
	"\x11server_message_id\x18\x03 \x01(\x04R\x0fserverMessageId\x12!\n" +
	"\ftimestamp_us\x18\x04 \x01(\x04R\vtimestampUs\x12$\n" +
	"\x0esender_user_id\x18\a \x01(\x04R\fsenderUserId\x12!\n" +
	"\fcontent_json\x18\b \x01(\fR\vcontentJson\x12-\n" +
	"\x04tags\x18\t \x03(\v2\x19.tiktok.im.v1.MetadataTagR\x04tagsB?Z=github.com/httpjamesm/matrix-tiktok/pkg/libtiktok/pb;tiktokpb"

var (
	file_tiktok_im_v1_im_proto_rawDescOnce sync.Once
	file_tiktok_im_v1_im_proto_rawDescData []byte
)

func file_tiktok_im_v1_im_proto_rawDescGZIP() []byte {
	file_tiktok_im_v1_im_proto_rawDescOnce.Do(func() {
		file_tiktok_im_v1_im_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_tiktok_im_v1_im_proto_rawDesc), len(file_tiktok_im_v1_im_proto_rawDesc)))
	})
	return file_tiktok_im_v1_im_proto_rawDescData
}

var file_tiktok_im_v1_im_proto_msgTypes = make([]protoimpl.MessageInfo, 36)
var file_tiktok_im_v1_im_proto_goTypes = []any{
	(*EmptyMessage)(nil),                     // 0: tiktok.im.v1.EmptyMessage
	(*MetadataKV)(nil),                       // 1: tiktok.im.v1.MetadataKV
	(*MetadataTag)(nil),                      // 2: tiktok.im.v1.MetadataTag
	(*InboxRequest)(nil),                     // 3: tiktok.im.v1.InboxRequest
	(*InboxRequestPayload)(nil),              // 4: tiktok.im.v1.InboxRequestPayload
	(*InboxInitRequest)(nil),                 // 5: tiktok.im.v1.InboxInitRequest
	(*InboxResponse)(nil),                    // 6: tiktok.im.v1.InboxResponse
	(*InboxResponsePayload)(nil),             // 7: tiktok.im.v1.InboxResponsePayload
	(*InboxConversationList)(nil),            // 8: tiktok.im.v1.InboxConversationList
	(*InboxConversationEntry)(nil),           // 9: tiktok.im.v1.InboxConversationEntry
	(*GetByConversationRequest)(nil),         // 10: tiktok.im.v1.GetByConversationRequest
	(*GetByConversationRequestPayload)(nil),  // 11: tiktok.im.v1.GetByConversationRequestPayload
	(*GetByConversationQuery)(nil),           // 12: tiktok.im.v1.GetByConversationQuery
	(*GetByConversationResponse)(nil),        // 13: tiktok.im.v1.GetByConversationResponse
	(*GetByConversationResponsePayload)(nil), // 14: tiktok.im.v1.GetByConversationResponsePayload
	(*ConversationMessageList)(nil),          // 15: tiktok.im.v1.ConversationMessageList
	(*ConversationMessageEntry)(nil),         // 16: tiktok.im.v1.ConversationMessageEntry
	(*SendRequest)(nil),                      // 17: tiktok.im.v1.SendRequest
	(*SendRequestPayload)(nil),               // 18: tiktok.im.v1.SendRequestPayload
	(*SendMessageBody)(nil),                  // 19: tiktok.im.v1.SendMessageBody
	(*SendResponse)(nil),                     // 20: tiktok.im.v1.SendResponse
	(*SendResponsePayload)(nil),              // 21: tiktok.im.v1.SendResponsePayload
	(*SendResponseBody)(nil),                 // 22: tiktok.im.v1.SendResponseBody
	(*ReactionRequest)(nil),                  // 23: tiktok.im.v1.ReactionRequest
	(*ReactionRequestPayload)(nil),           // 24: tiktok.im.v1.ReactionRequestPayload
	(*ReactionWrapper)(nil),                  // 25: tiktok.im.v1.ReactionWrapper
	(*ReactionBody)(nil),                     // 26: tiktok.im.v1.ReactionBody
	(*ReactionMutation)(nil),                 // 27: tiktok.im.v1.ReactionMutation
	(*ReactionSummary)(nil),                  // 28: tiktok.im.v1.ReactionSummary
	(*ReactionUsers)(nil),                    // 29: tiktok.im.v1.ReactionUsers
	(*ReactionUser)(nil),                     // 30: tiktok.im.v1.ReactionUser
	(*WebsocketFrame)(nil),                   // 31: tiktok.im.v1.WebsocketFrame
	(*WebsocketEnvelope)(nil),                // 32: tiktok.im.v1.WebsocketEnvelope
	(*WebsocketCommands)(nil),                // 33: tiktok.im.v1.WebsocketCommands
	(*WebsocketChat)(nil),                    // 34: tiktok.im.v1.WebsocketChat
	(*WebsocketMessageDetail)(nil),           // 35: tiktok.im.v1.WebsocketMessageDetail
}
var file_tiktok_im_v1_im_proto_depIdxs = []int32{
	0,  // 0: tiktok.im.v1.InboxRequest.options:type_name -> tiktok.im.v1.EmptyMessage
	4,  // 1: tiktok.im.v1.InboxRequest.payload:type_name -> tiktok.im.v1.InboxRequestPayload
	1,  // 2: tiktok.im.v1.InboxRequest.metadata:type_name -> tiktok.im.v1.MetadataKV
	5,  // 3: tiktok.im.v1.InboxRequestPayload.user_init_list:type_name -> tiktok.im.v1.InboxInitRequest
	7,  // 4: tiktok.im.v1.InboxResponse.payload:type_name -> tiktok.im.v1.InboxResponsePayload
	8,  // 5: tiktok.im.v1.InboxResponsePayload.user_init_list:type_name -> tiktok.im.v1.InboxConversationList
	9,  // 6: tiktok.im.v1.InboxConversationList.entries:type_name -> tiktok.im.v1.InboxConversationEntry
	0,  // 7: tiktok.im.v1.GetByConversationRequest.options:type_name -> tiktok.im.v1.EmptyMessage
	11, // 8: tiktok.im.v1.GetByConversationRequest.payload:type_name -> tiktok.im.v1.GetByConversationRequestPayload
	1,  // 9: tiktok.im.v1.GetByConversationRequest.metadata:type_name -> tiktok.im.v1.MetadataKV
	12, // 10: tiktok.im.v1.GetByConversationRequestPayload.query:type_name -> tiktok.im.v1.GetByConversationQuery
	14, // 11: tiktok.im.v1.GetByConversationResponse.payload:type_name -> tiktok.im.v1.GetByConversationResponsePayload
	15, // 12: tiktok.im.v1.GetByConversationResponsePayload.conversation:type_name -> tiktok.im.v1.ConversationMessageList
	16, // 13: tiktok.im.v1.ConversationMessageList.entries:type_name -> tiktok.im.v1.ConversationMessageEntry
	2,  // 14: tiktok.im.v1.ConversationMessageEntry.tags:type_name -> tiktok.im.v1.MetadataTag
	28, // 15: tiktok.im.v1.ConversationMessageEntry.reactions:type_name -> tiktok.im.v1.ReactionSummary
	0,  // 16: tiktok.im.v1.SendRequest.options:type_name -> tiktok.im.v1.EmptyMessage
	18, // 17: tiktok.im.v1.SendRequest.payload:type_name -> tiktok.im.v1.SendRequestPayload
	1,  // 18: tiktok.im.v1.SendRequest.metadata:type_name -> tiktok.im.v1.MetadataKV
	19, // 19: tiktok.im.v1.SendRequestPayload.send:type_name -> tiktok.im.v1.SendMessageBody
	2,  // 20: tiktok.im.v1.SendMessageBody.tags:type_name -> tiktok.im.v1.MetadataTag
	21, // 21: tiktok.im.v1.SendResponse.primary:type_name -> tiktok.im.v1.SendResponsePayload
	21, // 22: tiktok.im.v1.SendResponse.fallback:type_name -> tiktok.im.v1.SendResponsePayload
	22, // 23: tiktok.im.v1.SendResponsePayload.send:type_name -> tiktok.im.v1.SendResponseBody
	0,  // 24: tiktok.im.v1.ReactionRequest.options:type_name -> tiktok.im.v1.EmptyMessage
	24, // 25: tiktok.im.v1.ReactionRequest.payload:type_name -> tiktok.im.v1.ReactionRequestPayload
	1,  // 26: tiktok.im.v1.ReactionRequest.metadata:type_name -> tiktok.im.v1.MetadataKV
	25, // 27: tiktok.im.v1.ReactionRequestPayload.wrapper:type_name -> tiktok.im.v1.ReactionWrapper
	26, // 28: tiktok.im.v1.ReactionWrapper.body:type_name -> tiktok.im.v1.ReactionBody
	27, // 29: tiktok.im.v1.ReactionBody.reactions:type_name -> tiktok.im.v1.ReactionMutation
	29, // 30: tiktok.im.v1.ReactionSummary.users:type_name -> tiktok.im.v1.ReactionUsers
	30, // 31: tiktok.im.v1.ReactionUsers.entries:type_name -> tiktok.im.v1.ReactionUser
	32, // 32: tiktok.im.v1.WebsocketFrame.envelope:type_name -> tiktok.im.v1.WebsocketEnvelope
	33, // 33: tiktok.im.v1.WebsocketEnvelope.commands:type_name -> tiktok.im.v1.WebsocketCommands
	34, // 34: tiktok.im.v1.WebsocketCommands.chat:type_name -> tiktok.im.v1.WebsocketChat
	35, // 35: tiktok.im.v1.WebsocketChat.detail:type_name -> tiktok.im.v1.WebsocketMessageDetail
	2,  // 36: tiktok.im.v1.WebsocketMessageDetail.tags:type_name -> tiktok.im.v1.MetadataTag
	37, // [37:37] is the sub-list for method output_type
	37, // [37:37] is the sub-list for method input_type
	37, // [37:37] is the sub-list for extension type_name
	37, // [37:37] is the sub-list for extension extendee
	0,  // [0:37] is the sub-list for field type_name
}

func init() { file_tiktok_im_v1_im_proto_init() }
func file_tiktok_im_v1_im_proto_init() {
	if File_tiktok_im_v1_im_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_tiktok_im_v1_im_proto_rawDesc), len(file_tiktok_im_v1_im_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   36,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_tiktok_im_v1_im_proto_goTypes,
		DependencyIndexes: file_tiktok_im_v1_im_proto_depIdxs,
		MessageInfos:      file_tiktok_im_v1_im_proto_msgTypes,
	}.Build()
	File_tiktok_im_v1_im_proto = out.File
	file_tiktok_im_v1_im_proto_goTypes = nil
	file_tiktok_im_v1_im_proto_depIdxs = nil
}
